require('dotenv').config(); const express=require('express'); const cors=require('cors'); const jwt=require('jsonwebtoken'); const bcrypt=require('bcryptjs'); const {v4:uuidv4}=require('uuid'); const db=require('./db/database'); const news=require('./services/news'); const agent=require('./agent/agent'); const ollama=require('./services/ollama');
const app=express(); app.use(cors()); app.use(express.json()); app.use(express.static('public')); const SECRET=process.env.JWT_SECRET||'dev-secret';
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch{return res.status(401).json({error:'Authentication required'})}}
app.get('/api/health',async(_,res)=>res.json({ok:true,service:'world-in-brief',ollama:await ollama.available(),time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{try{const {username,email,password}=req.body;if(!username||!email||!password)return res.status(400).json({error:'username, email and password required'});const hash=await bcrypt.hash(password,10);const x=db.prepare('INSERT INTO users(username,email,password_hash) VALUES(?,?,?)').run(username,email,hash);res.json({token:jwt.sign({id:x.lastInsertRowid,username,role:'user'},SECRET,{expiresIn:'7d'})})}catch(e){res.status(409).json({error:'User already exists'})}});
app.post('/api/auth/login',async(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=? OR username=?').get(req.body.email,req.body.email);if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Invalid credentials'});res.json({token:jwt.sign({id:u.id,username:u.username,role:u.role},SECRET,{expiresIn:'7d'}),user:{id:u.id,username:u.username,role:u.role}})});
app.get('/api/news',async(req,res)=>{if(req.query.refresh==='1')await news.refresh();res.json(news.list(req.query))});
app.post('/api/news/refresh',async(_,res)=>res.json({fetched:await news.refresh()}));
app.post('/api/agent/chat',async(req,res)=>{try{const r=await agent.run(req.body.query||'',req.user?.id);res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/bookmarks/:id',auth,(req,res)=>{db.prepare('INSERT OR IGNORE INTO bookmarks(user_id,article_id) VALUES(?,?)').run(req.user.id,req.params.id);res.json({ok:true})});
app.delete('/api/bookmarks/:id',auth,(req,res)=>{db.prepare('DELETE FROM bookmarks WHERE user_id=? AND article_id=?').run(req.user.id,req.params.id);res.json({ok:true})});
app.get('/api/bookmarks',auth,(req,res)=>res.json(db.prepare('SELECT a.* FROM articles a JOIN bookmarks b ON a.id=b.article_id WHERE b.user_id=? ORDER BY b.created_at DESC').all(req.user.id)));
app.post('/api/history/:id',auth,(req,res)=>{db.prepare('INSERT INTO history(user_id,article_id) VALUES(?,?)').run(req.user.id,req.params.id);res.json({ok:true})});
app.get('/api/trending',(req,res)=>res.json(db.prepare(`SELECT a.category,a.title,COUNT(h.article_id) reads FROM articles a LEFT JOIN history h ON a.id=h.article_id GROUP BY a.id ORDER BY reads DESC,a.published_at DESC LIMIT 10`).all()));
app.get('/api/analytics',(req,res)=>{res.json({articles:db.prepare('SELECT COUNT(*) c FROM articles').get().c,users:db.prepare('SELECT COUNT(*) c FROM users').get().c,agentRuns:db.prepare('SELECT COUNT(*) c FROM agent_runs').get().c,successfulRuns:db.prepare("SELECT COUNT(*) c FROM agent_runs WHERE status='completed'").get().c,avgLatency:db.prepare('SELECT ROUND(AVG(duration_ms),0) v FROM agent_runs WHERE duration_ms IS NOT NULL').get().v||0})});
app.post('/api/feedback',async(req,res)=>{db.prepare('INSERT INTO feedback(user_id,type,content) VALUES(?,?,?)').run(req.user?.id||null,req.body.type||'general',req.body.content||'');res.json({ok:true})});
app.get('/api/agent/runs',auth,(req,res)=>res.json(db.prepare('SELECT id,query,plan,status,duration_ms,created_at FROM agent_runs ORDER BY created_at DESC LIMIT 25').all()));
(async()=>{await news.refresh();const port=Number(process.env.PORT||5000);app.listen(port,()=>console.log(`World In Brief running at http://localhost:${port}`));})();
